[package]
name = "backup_v0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.9"
sha2 = "0.9"
rayon = "1.8.0"